import { mkdir, readFile, readdir, rm, writeFile } from 'node:fs/promises';
import { basename, dirname, extname, join, relative, resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '..');
const API_VERSION = '2025-09-03';
const GENERATED_MARKER = '<!-- Generated from Notion. Do not edit this file directly. -->';

await loadEnv(join(ROOT, '.env'));

const token = process.env.NOTION_API_KEY;
const configuredDataSourceId = process.env.NOTION_DATA_SOURCE_ID;
const configuredDatabaseId = process.env.NOTION_DATABASE_ID;
const contentRoot = resolve(ROOT, process.env.NOTION_CONTENT_DIR || 'content/posts');
const propertyNames = {
  title: process.env.NOTION_TITLE_PROPERTY || 'Title',
  slug: process.env.NOTION_SLUG_PROPERTY || 'Slug',
  published: process.env.NOTION_PUBLISHED_PROPERTY || 'Published',
  date: process.env.NOTION_DATE_PROPERTY || 'Date',
  description: process.env.NOTION_DESCRIPTION_PROPERTY || 'Description',
  tags: process.env.NOTION_TAGS_PROPERTY || 'Tags',
  categories: process.env.NOTION_CATEGORIES_PROPERTY || 'Categories',
  section: process.env.NOTION_SECTION_PROPERTY || 'Section',
};

if (!token || (!configuredDataSourceId && !configuredDatabaseId)) {
  console.log('Notion sync skipped: set NOTION_API_KEY and NOTION_DATA_SOURCE_ID (or NOTION_DATABASE_ID).');
  process.exit(0);
}

const dataSourceId = configuredDataSourceId || await findDataSourceId(configuredDatabaseId);
const pages = await queryPublishedPages(dataSourceId);
const generatedPaths = new Set();

for (const page of pages) {
  const title = readTitle(page.properties[propertyNames.title]) || 'Untitled';
  const requestedSlug = readText(page.properties[propertyNames.slug]);
  const slug = slugify(requestedSlug || title || page.id);
  const requestedSection = readSelect(page.properties[propertyNames.section]);
  const section = safePathSegment(requestedSection);
  const pageRoot = section ? join(contentRoot, '..', section, slug) : join(contentRoot, slug);
  const outputPath = join(pageRoot, 'index.md');
  const assetRoot = join(pageRoot, 'notion-assets');

  await mkdir(assetRoot, { recursive: true });

  const blocks = await listBlockChildren(page.id);
  const body = await blocksToMarkdown(blocks, assetRoot);
  const cover = await downloadCover(page, assetRoot);
  const frontMatter = buildFrontMatter({
    title,
    description: readText(page.properties[propertyNames.description]),
    date: readDate(page.properties[propertyNames.date]) || page.created_time,
    lastmod: page.last_edited_time,
    tags: readMultiSelect(page.properties[propertyNames.tags]),
    categories: readMultiSelect(page.properties[propertyNames.categories]),
    cover,
    notionId: page.id,
  });

  await writeFile(outputPath, `${frontMatter}\n${GENERATED_MARKER}\n\n${body.trim()}\n`, 'utf8');
  generatedPaths.add(outputPath);
  console.log(`Synced: ${relative(ROOT, outputPath)}`);
}

await removeStaleGeneratedPosts(contentRoot, generatedPaths);
console.log(`Notion sync complete: ${pages.length} published page(s).`);

async function notionRequest(path, options = {}) {
  const response = await fetch(`https://api.notion.com/v1${path}`, {
    ...options,
    headers: {
      Authorization: `Bearer ${token}`,
      'Notion-Version': API_VERSION,
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

  if (!response.ok) {
    const detail = await response.text();
    throw new Error(`Notion API ${response.status}: ${detail}`);
  }

  return response.json();
}

async function findDataSourceId(databaseId) {
  const database = await notionRequest(`/databases/${databaseId}`);
  const firstDataSource = database.data_sources?.[0];
  if (!firstDataSource?.id) {
    throw new Error('The Notion database has no data source. Set NOTION_DATA_SOURCE_ID directly.');
  }
  return firstDataSource.id;
}

async function queryPublishedPages(sourceId) {
  const results = [];
  let cursor;

  do {
    const payload = {
      page_size: 100,
      filter: {
        property: propertyNames.published,
        checkbox: { equals: true },
      },
      sorts: [{ property: propertyNames.date, direction: 'descending' }],
    };
    if (cursor) payload.start_cursor = cursor;

    const response = await notionRequest(`/data_sources/${sourceId}/query`, {
      method: 'POST',
      body: JSON.stringify(payload),
    });
    results.push(...response.results.filter((item) => item.object === 'page'));
    cursor = response.has_more ? response.next_cursor : undefined;
  } while (cursor);

  return results;
}

async function listBlockChildren(blockId) {
  const results = [];
  let cursor;

  do {
    const query = new URLSearchParams({ page_size: '100' });
    if (cursor) query.set('start_cursor', cursor);
    const response = await notionRequest(`/blocks/${blockId}/children?${query}`);
    results.push(...response.results);
    cursor = response.has_more ? response.next_cursor : undefined;
  } while (cursor);

  return results;
}

async function blocksToMarkdown(blocks, assetRoot, depth = 0) {
  const lines = [];

  for (const block of blocks) {
    const value = block[block.type] || {};
    const text = richTextToMarkdown(value.rich_text || []);
    let markdown = '';

    switch (block.type) {
      case 'paragraph':
        markdown = text;
        break;
      case 'heading_1':
        markdown = `# ${text}`;
        break;
      case 'heading_2':
        markdown = `## ${text}`;
        break;
      case 'heading_3':
      case 'heading_4':
        markdown = `### ${text}`;
        break;
      case 'bulleted_list_item':
        markdown = `${'  '.repeat(depth)}- ${text}`;
        break;
      case 'numbered_list_item':
        markdown = `${'  '.repeat(depth)}1. ${text}`;
        break;
      case 'to_do':
        markdown = `${'  '.repeat(depth)}- [${value.checked ? 'x' : ' '}] ${text}`;
        break;
      case 'quote':
        markdown = text.split('\n').map((line) => `> ${line}`).join('\n');
        break;
      case 'callout': {
        const icon = value.icon?.emoji ? `${value.icon.emoji} ` : '';
        markdown = `> ${icon}${text}`;
        break;
      }
      case 'code':
        markdown = `\`\`\`${value.language || ''}\n${plainText(value.rich_text || [])}\n\`\`\``;
        break;
      case 'divider':
        markdown = '---';
        break;
      case 'equation':
        markdown = `$$\n${value.expression || ''}\n$$`;
        break;
      case 'image': {
        const url = value.file?.url || value.external?.url;
        if (url) {
          const localPath = await downloadAsset(url, assetRoot, block.id, guessExtension(url, 'jpg'));
          markdown = `![${escapeMarkdown(value.caption?.map((item) => item.plain_text).join('') || '')}](${localPath})`;
        }
        break;
      }
      case 'file':
      case 'pdf': {
        const url = value.file?.url || value.external?.url;
        if (url) {
          const name = value.name || `attachment-${block.id}`;
          const localPath = await downloadAsset(url, assetRoot, name, guessExtension(url, 'bin'));
          markdown = `[${escapeMarkdown(name)}](${localPath})`;
        }
        break;
      }
      case 'bookmark':
      case 'embed':
      case 'link_preview':
        markdown = value.url ? `[${escapeMarkdown(value.caption?.[0]?.plain_text || value.url)}](${value.url})` : '';
        break;
      case 'video':
      case 'audio':
        markdown = value.external?.url ? `[${block.type}](${value.external.url})` : '';
        break;
      case 'table': {
        const rows = await listBlockChildren(block.id);
        markdown = tableToMarkdown(rows, value.has_column_header);
        break;
      }
      case 'table_row':
        break;
      case 'child_page':
        markdown = `### ${escapeMarkdown(value.title || '하위 페이지')}`;
        break;
      case 'toggle':
        markdown = `**${text}**`;
        break;
      case 'synced_block':
      case 'column_list':
      case 'column':
        break;
      default:
        if (text) markdown = text;
    }

    if (markdown) lines.push(markdown);

    if (block.has_children && block.type !== 'table') {
      const children = await listBlockChildren(block.id);
      const childMarkdown = await blocksToMarkdown(
        children,
        assetRoot,
        ['bulleted_list_item', 'numbered_list_item', 'to_do'].includes(block.type) ? depth + 1 : depth,
      );
      if (childMarkdown.trim()) lines.push(childMarkdown.trim());
    }

    if (markdown && !['bulleted_list_item', 'numbered_list_item', 'to_do'].includes(block.type)) {
      lines.push('');
    }
  }

  return lines.join('\n').replace(/\n{3,}/g, '\n\n');
}

function tableToMarkdown(rows, hasHeader) {
  if (!rows.length) return '';
  const cells = rows.map((row) =>
    (row.table_row?.cells || []).map((cell) => richTextToMarkdown(cell).replaceAll('|', '\\|')),
  );
  const width = Math.max(...cells.map((row) => row.length));
  const normalized = cells.map((row) => [...row, ...Array(width - row.length).fill('')]);
  const first = normalized[0];
  const body = hasHeader ? normalized.slice(1) : normalized;
  const header = hasHeader ? first : Array(width).fill('');
  return [
    `| ${header.join(' | ')} |`,
    `| ${Array(width).fill('---').join(' | ')} |`,
    ...body.map((row) => `| ${row.join(' | ')} |`),
  ].join('\n');
}

function richTextToMarkdown(items) {
  return items.map((item) => {
    let text = item.type === 'equation' ? `$${item.equation?.expression || ''}$` : item.plain_text || '';
    text = escapeMarkdown(text);
    const annotations = item.annotations || {};

    if (annotations.code) text = `\`${text.replaceAll('`', '\\`')}\``;
    if (annotations.bold) text = `**${text}**`;
    if (annotations.italic) text = `_${text}_`;
    if (annotations.strikethrough) text = `~~${text}~~`;
    if (item.href) text = `[${text}](${item.href})`;
    return text;
  }).join('');
}

function plainText(items) {
  return items.map((item) => item.plain_text || item.equation?.expression || '').join('');
}

async function downloadCover(page, assetRoot) {
  const url = page.cover?.file?.url || page.cover?.external?.url;
  if (!url) return '';
  return downloadAsset(url, assetRoot, 'cover', guessExtension(url, 'jpg'));
}

async function downloadAsset(url, assetRoot, rawName, fallbackExtension) {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`Asset download failed (${response.status}): ${url}`);

  const contentType = response.headers.get('content-type')?.split(';')[0];
  const extension = extensionFromContentType(contentType) || fallbackExtension;
  const fileName = `${slugify(basename(rawName, extname(rawName))) || 'asset'}-${shortId(rawName)}.${extension}`;
  const outputPath = join(assetRoot, fileName);
  await writeFile(outputPath, Buffer.from(await response.arrayBuffer()));
  return `notion-assets/${fileName}`;
}

function buildFrontMatter({ title, description, date, lastmod, tags, categories, cover, notionId }) {
  const fields = [
    '---',
    `title: ${yamlString(title)}`,
    'draft: false',
    `date: ${yamlString(date)}`,
    `lastmod: ${yamlString(lastmod)}`,
    `description: ${yamlString(description || '')}`,
    `notion_id: ${yamlString(notionId)}`,
  ];
  if (cover) fields.push(`cover: ${yamlString(cover)}`);
  fields.push(...yamlList('categories', categories), ...yamlList('tags', tags), '---');
  return fields.join('\n');
}

function yamlList(key, values) {
  if (!values.length) return [`${key}: []`];
  return [`${key}:`, ...values.map((value) => `  - ${yamlString(value)}`)];
}

function yamlString(value) {
  return JSON.stringify(String(value ?? ''));
}

function readTitle(property) {
  return plainText(property?.title || []);
}

function readText(property) {
  if (!property) return '';
  if (property.type === 'rich_text') return plainText(property.rich_text || []);
  if (property.type === 'url') return property.url || '';
  if (property.type === 'formula') return String(property.formula?.string || '');
  return '';
}

function readDate(property) {
  return property?.date?.start || '';
}

function readMultiSelect(property) {
  return (property?.multi_select || []).map((item) => item.name).filter(Boolean);
}

function readSelect(property) {
  return property?.select?.name || property?.status?.name || '';
}

function escapeMarkdown(value) {
  return String(value).replace(/([\\[\]<>])/g, '\\$1');
}

function slugify(value) {
  return String(value)
    .normalize('NFKD')
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9가-힣]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 100);
}

function safePathSegment(value) {
  return slugify(value).replaceAll('..', '');
}

function shortId(value) {
  return String(value).replaceAll('-', '').slice(-8) || 'asset';
}

function guessExtension(url, fallback) {
  try {
    const extension = extname(new URL(url).pathname).slice(1).toLowerCase();
    return /^[a-z0-9]{2,5}$/.test(extension) ? extension : fallback;
  } catch {
    return fallback;
  }
}

function extensionFromContentType(contentType) {
  return {
    'image/jpeg': 'jpg',
    'image/png': 'png',
    'image/gif': 'gif',
    'image/webp': 'webp',
    'image/svg+xml': 'svg',
    'application/pdf': 'pdf',
  }[contentType];
}

async function removeStaleGeneratedPosts(root, activePaths) {
  const generatedFiles = await findGeneratedIndexes(resolve(ROOT, 'content'));
  for (const indexPath of generatedFiles) {
    if (activePaths.has(indexPath)) continue;
    await rm(dirname(indexPath), { recursive: true, force: true });
    console.log(`Removed unpublished page: ${relative(ROOT, indexPath)}`);
  }
}

async function findGeneratedIndexes(directory) {
  const matches = [];
  let entries = [];
  try {
    entries = await readdir(directory, { withFileTypes: true });
  } catch {
    return matches;
  }

  for (const entry of entries) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) {
      matches.push(...await findGeneratedIndexes(path));
    } else if (entry.name === 'index.md') {
      try {
        const content = await readFile(path, 'utf8');
        if (content.includes(GENERATED_MARKER)) matches.push(path);
      } catch {
        // Ignore files that disappear during a concurrent local edit.
      }
    }
  }
  return matches;
}

async function loadEnv(path) {
  try {
    const source = await readFile(path, 'utf8');
    for (const line of source.split(/\r?\n/)) {
      const match = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
      if (!match || process.env[match[1]] !== undefined) continue;
      let value = match[2];
      if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
        value = value.slice(1, -1);
      }
      process.env[match[1]] = value;
    }
  } catch {
    // .env is optional; GitHub Actions supplies environment variables directly.
  }
}
